[input_data]

    [input_data.forward]
        path = "data/inputRaw/forward"
        category = "forward"

    [input_data.back]
        path = "data/inputRaw/back"
        category = "back"

    [input_data.left]
        path = "data/inputRaw/left"
        category = "left"

    [input_data.right]
        path = "data/inputRaw/right"
        category = "right"

    [input_data.stop]
        path = "data/inputRaw/stop"
        category = "stop"


[synthesis]
    # The number of samples to synthesize
    number_output_samples = 20000
    # The minimum number of words per sample
    # (one word is one input data file)
    min_number_of_words = 0
    # The maximum number of words per sample
    max_number_of_words = 1
    # The sample length in seconds
    max_length_seconds = 4
    # The sample rate to use for length calculations
    sample_rate_hz = 44100
    # The path to the training database
    db_path = "trainingData/trainingData.db"

    # Config for exporting synthesis results

    [synthesis.synthesisDataSave]
        # Whether the synthesised samples shall be exported as mp3
        do_export_synthesis_data = false
        # The path to the export folder
        data_path = "data/outputSynthesis"
        # The parameters for the export
        sample_width = 2
        channels = 1
        sample_rate_hz = 44100
        # Whether the samples shall be saved in the training database
        save_synthesis_data_in_db = true

    # Config for the batch processors which require config
    # Section has to be called as the class is called

    # Background noise addition
    [synthesis.AddBackgroundNoiseProcessor]
        backgrounds_path = "data/inputRaw/background"
        sample_width = 2
        # Only apply the background to the whole sample
        apply_probability = 0

    # Background voice addition
    [synthesis.AddBackgroundVoiceProcessor]
        backgrounds_path = "data/inputRaw/negatives"
        # Maximum number of samples that should be added in the background
        max_background_sample_number = 7

        sample_width = 2
        channels = 1
        sample_rate_hz = 44100
        # Only apply the background to the whole sample
        apply_probability = 0

    [synthesis.AdjustVolumeProcessor]
        # The maximum increase level for the audio samples in percent. Has to be in a
        # range of 0 - 100
        max_volume_increase_percent = 10
        # The maximum decrease level for the audio samples in percent Has to be in a
        # range of 0 - 100
        max_volume_decrease_percent = 40

    [synthesis.DistortionProcessor]
        # The maximum increase level for the audio samples in percent. Has to be in a
        # range of 0 - 100
        max_volume_increase_percent = 35
        # The maximum decrease level for the audio samples in percent Has to be in a
        # range of 0 - 100
        max_volume_decrease_percent = -25

    [synthesis.AdjustPlaybackSpeedProcessor]
        # The maximum increase level for the audio sample speed in percent. Has to be in a
        # range of 0 - 100
        max_speed_increase_percent = 25
        # The maximum decrease level for the audio sample speed in percent Has to be in a
        # range of 0 - 100
        max_speed_decrease_percent = 25

    # Synthesis step specific config
    [synthesis.PreStitching]
        # The minimum number of processors to apply to a sample
        # e.g. background noise addition or speeding up samples
        min_number_processors = 1
        # The maximum number of processors to apply to a sample
        max_number_processors = 3

    [synthesis.PostStitching]
        # The minimum number of processors to apply to a sample
        # e.g. background noise addition or speeding up samples
        min_number_processors = 1
        # The maximum number of processors to apply to a sample
        max_number_processors = 3

        # Apply the background noise for post stitching
        [synthesis.PostStitching.AddBackgroundNoiseProcessor]
            # Only apply the background to the whole sample
            apply_probability = 0.5

        # Apply the background voices for post stitching
        [synthesis.PostStitching.AddBackgroundVoiceProcessor]
            # Only apply the background to the whole sample
            apply_probability = 0.5

        # Do not change the playback speed post stitching
        [synthesis.PostStitching.AdjustPlaybackSpeedProcessor]
            apply_probability = 0.0

[training]
    # The batch size zo use
    batch_size = 512
    # The learn rate to use
    learn_rate = 0.02
    # The number of epochs to adjust the learn rate after, use -1 for no adjusting
    # The adjusting is done every time the threshold is reached
    adjust_learn_rate_after_epochs = 40
    # The multiplicator for the learn rate after adjusting
    # i.e. 0.9 would make the learn rate 90% of the previous one
    adjust_learn_rate_multiplier = 0.5
    # The weight decay to use
    weight_decay = 0
    # The number of epochs to train
    number_of_epochs = 100
    # The maximum number of samples to use for training or -1 for all samples
    max_number_of_samples = -1
    # The ratio to use for test and training data
    # e.g. 0.2 == 20% test data
    test_train_data_ratio = 0.2
    # The seed to use for the split into train and test, use -1 for a random seed
    train_test_split_seed = -1
    # The path to save checkpoints to
    checkpoint_path = "checkpoints"
    # The name to use for saving the best model, this is relative to the checkpoint path
    best_model_path = "best_model"
    # The number of epochs to wait between saving checkpoints
    checkpoint_epoch_interval = 10
    # Which checkpoint to load, use the path of the checkpoint relative to the checkpoint path
    load_checkpoint = "best_model.pth"

[inference]
    # The length of the recording in seconds
    recording_length = 4
